version: "3.9"

services:
  api:
    build: 
      context: .
      args:
        BUILD_CONFIGURATION: Debug
    env_file:
      - api.env
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:16.2
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}