version: "3.9"

services:
  api:
    build: 
      context: ./API
      args:
        BUILD_CONFIGURATION: ${CONFIGURATION}
    environment:
      - ConnectionStrings__DefaultConnectionString=Host=db;Port=${DB_PORT};Database=LogsMonitor;Username=postgres;Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "${API_PORT}:80"
    depends_on:
      - db
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}