version: "3.9"

services:
  api:
    build: 
      context: .
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      - ConnectionStrings__DefaultConnectionString=Host=db;Port=5432;Database=LogsMonitor;Username=postgres;Password=123Qwe
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123Qwe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}